### ISSUE TITLE
Termux debian

### ISSUE THREAD

**Issue by molafir** [TheHamkerCat/Telegram_VC_Bot#110]
Traceback (most recent call last):                        File "/root/Telegram_VC_Bot/main.py", line 21, in <module>                                                        from functions import (CHAT_ID, app, get_default_service, play_song,                                          File "/root/Telegram_VC_Bot/functions.py", line 6, in <module>                                                    import aiofiles                                     ModuleNotFoundError: No module named 'aiofiles'

--------
Traceback (most recent call last):                        File "/root/Telegram_VC_Bot/main.py", line 21, in <module>                                                        from functions import (CHAT_ID, app, get_default_service, play_song,                                          File "/root/Telegram_VC_Bot/functions.py", line 9, in <module>                                                    from aiohttp import ClientSession                   ModuleNotFoundError: No module named 'aiohttp'

-------

Traceback (most recent call last):                        File "/root/Telegram_VC_Bot/main.py", line 21, in <module>                                                        from functions import (CHAT_ID, app, get_default_service, play_song,                                          File "/root/Telegram_VC_Bot/functions.py", line 10, in <module>                                                   from PIL import Image, ImageDraw, ImageFont         ModuleNotFoundError: No module named 'PIL'

-------
Traceback (most recent call last):                        File "/root/Telegram_VC_Bot/main.py", line 21, in <module>                                                        from functions import (CHAT_ID, app, get_default_service, play_song,                                          File "/root/Telegram_VC_Bot/functions.py", line 15, in <module>                                                   from Python_ARQ import ARQ                          ModuleNotFoundError: No module named 'Python_ARQ'

**Comment by AnonymousR1025** [comment]
That's not a issue, just install that packages or simply use requirements.txt for installing all of them.
