### ISSUE TITLE
showing key error in config file

### ISSUE THREAD

**Issue by Lucifer7535** [thehamkercat/Telegram_VC_Bot#40]
2021-04-04T17:57:37.121624+00:00 app[worker.1]: Traceback (most recent call last):
2021-04-04T17:57:37.121670+00:00 app[worker.1]:   File "main.py", line 19, in <module>
2021-04-04T17:57:37.121875+00:00 app[worker.1]:     from config import (
2021-04-04T17:57:37.121902+00:00 app[worker.1]:   File "/app/config.py", line 7, in <module>
2021-04-04T17:57:37.122050+00:00 app[worker.1]:     API_ID = int(environ["1389947"])
2021-04-04T17:57:37.130217+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/os.py", line 669, in __getitem__
2021-04-04T17:57:37.130945+00:00 app[worker.1]:     raise KeyError(key) from None
2021-04-04T17:57:37.131000+00:00 app[worker.1]: KeyError: '1389947'

**Comment by Lucifer7535** [comment]
i got help from support group

**Comment by rktiwari00** [comment]
> i got help from support group

Please share here
